# Generated by Django 4.2.26 on 2025-11-27 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Voting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                ("start_date", models.DateTimeField(verbose_name="Data de Início")),
                ("end_date", models.DateTimeField(verbose_name="Data de Término")),
                (
                    "requires_presence",
                    models.BooleanField(default=True, verbose_name="Requer Presença"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_votings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Votação",
                "verbose_name_plural": "Votações",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VotingOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option_text",
                    models.CharField(max_length=200, verbose_name="Texto da Opção"),
                ),
                ("option_letter", models.CharField(max_length=1, verbose_name="Letra")),
                (
                    "votes_count",
                    models.IntegerField(default=0, verbose_name="Contagem de Votos"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "voting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="business.voting",
                        verbose_name="Votação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opção de Votação",
                "verbose_name_plural": "Opções de Votação",
                "ordering": ["option_letter"],
                "unique_together": {("voting", "option_letter")},
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Votado em"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="business.votingoption",
                        verbose_name="Opção",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
                (
                    "voting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="business.voting",
                        verbose_name="Votação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voto",
                "verbose_name_plural": "Votos",
                "ordering": ["-voted_at"],
                "unique_together": {("voting", "user")},
            },
        ),
    ]
