# Generated by Django 4.2.26 on 2025-11-27 16:23

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0002_voting_votingoption_vote"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        # Criar modelo Meeting
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('meeting_date', models.DateField(verbose_name='Data da Reunião')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Encerrado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_meetings', to='auth.user', verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Reunião',
                'verbose_name_plural': 'Reuniões',
                'ordering': ['-meeting_date', '-created_at'],
            },
        ),
        # Alterar unique_together primeiro (remover o antigo)
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together=set(),
        ),
        # Adicionar campo meeting ao Presence
        migrations.AddField(
            model_name='presence',
            name='meeting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='business.meeting', verbose_name='Reunião'),
            preserve_default=False,
        ),
        # Criar reunião padrão
        migrations.RunSQL(
            """
            INSERT INTO business_meeting (title, meeting_date, is_active, created_at, created_by_id)
            SELECT 'Reunião Padrão - Migração', '2024-01-01', 0, '2024-01-01 00:00:00', id
            FROM auth_user
            WHERE is_superuser = 1
            LIMIT 1
            """,
            reverse_sql="DELETE FROM business_meeting WHERE title = 'Reunião Padrão - Migração'"
        ),
        # Remover campo meeting_date
        migrations.RemoveField(
            model_name='presence',
            name='meeting_date',
        ),
        # Alterar unique_together (adicionar o novo)
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together={('user', 'meeting')},
        ),
        # Alterar ordering no Meta
        migrations.AlterModelOptions(
            name='presence',
            options={
                'ordering': ['meeting__meeting_date', 'user__username'],
                'verbose_name': 'Presença',
                'verbose_name_plural': 'Presenças'
            },
        ),
        # Alterar default do campo present
        migrations.AlterField(
            model_name='presence',
            name='present',
            field=models.BooleanField(default=False, verbose_name='Presente'),
        ),
    ]
