# Generated by Django 4.2.26 on 2025-11-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0003_auto_20251127_1323"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
